In [15]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sns

pd.set_option('display.max_columns', None)

1.Procedo a cargar los datos del archivo CSV y realizo algunas modificaciones en las columnas. Despues de ell mostramos resumen de la info.

In [ ]:
#Cargo el archivo csv
df_bank = df_bank_additional = pd.read_csv('bank-additional.csv')
df_bank = df_bank_additional = pd.read_csv('./Data_folder/bank-additional.csv')

FileNotFoundError: [Errno 2] No such file or directory: './Data_folder/bank-additional.csv'

In [ ]:
#Me aseguro que las columnas tengan nombres en minúsculas
df_bank.columns = df_bank_additional.columns.str.lower()
# Elimino columna 'unnamed: 0'que es innecesaria
df_bank.drop(columns ='unnamed: 0' , axis=1, inplace=True)
#Renombro la columna 'y' a 'subscribed' para mayor claridad
df_bank.rename(columns={'y': 'subscribe'}, inplace=True) 
#Renombro la columna 'id_' por 'id' para poder hacer merge con el otro dataset a través de esta columna
df_bank.rename(columns={'id_': 'id'}, inplace=True)
# Verifico que no haya duplicados
print(df_bank.duplicated('id').sum())                                                                                 
#Obtenemos la info sobre la cantidad de datos (columnas y filas) y tipos de variables 
df_bank.info() 
#Mostramos un resumen de las primeras filas y columnas del archivo
df_bank.head()

0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  float64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  object
 15  cons.conf.idx   43000 non-null  object
 16  euribor3m       33744 non-null  object
 17  nr.employed     43000 non-null  object
 18  subscribe       43000 non-null  object
 19  date            42752 non-null  object
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id              43000 non-null  object
dtypes: float64(7), int64(4), object(12)
memory usage: 7.5+ MB

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,subscribe,date,latitude,longitude,id
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

2. Realizo lo mismo para el archivo XLSX.

In [ ]:
#Procedo con los mismos pasos para el archivo xlsx
# Leer todas las hojas del Excel
excel_path = 'customer-details.xlsx'
all_sheets = pd.read_excel(excel_path, sheet_name=None)

# Unir todas las hojas en un solo DataFrame
df_customer = df_customer_details = pd.concat(all_sheets.values(), ignore_index=True)

# Verificar duplicados en IDs
print(df_customer['ID'].duplicated().sum())

0

In [ ]:
#Me aseguro que las columnas tengan nombres en minúsculas
df_customer.columns = df_customer.columns.str.lower()
# Elimino columna 'unnamed: 0'que es innecesaria
df_customer.drop(columns ='unnamed: 0' , axis=1, inplace=True)
#Renombro la columna 'ID' por 'id' para poder hacer merge con el otro dataset
df_customer.rename(columns={'ID': 'id'}, inplace=True)                                                                                       
#Obtenemos la info sobre la cantidad de datos (columnas y filas) y tipos de variables 
df_customer.info() 
#Mostramos un resumen de las primeras filas y columnas del archivo
df_customer.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   income             43170 non-null  int64
 1   kidhome            43170 non-null  int64
 2   teenhome           43170 non-null  int64
 3   dt_customer        43170 non-null  datetime64[ns]
 4   numwebvisitsmonth  43170 non-null  int64
 5   id                 43170 non-null  object
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 2.0+ MB

,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,id
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

3. Uno los dos datasets a través de sus respectivas columnas 'id' que es la referencia de las clientes y puede servir como clave única. Acabaré de realizar limpieza final de datos

In [ ]:
# Realizar outer join (todos los registros de ambos DataFrames)
df_merged = df_bank.merge(df_customer, on='id', how='outer')
# Tamaños
print("Tamaño df_bank:", df_bank.shape)
print("Tamaño df_customer:", df_customer.shape)
print("Tamaño df_merged (outer):", df_merged.shape)

df_merged.info()
df_merged.head()

Tamaño df_bank: (43000, 23)
Tamaño df_customer: (43170, 6)
Tamaño df_merged (outer): (43170, 28)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                37880 non-null  float64
 1   job                42655 non-null  object
 2   marital            42915 non-null  object
 3   education          41193 non-null  object
 4   default            34019 non-null  float64
 5   housing            41974 non-null  float64
 6   loan               41974 non-null  float64
 7   contact            43000 non-null  object
 8   duration           43000 non-null  float64
 9   campaign           43000 non-null  float64
 10  pdays              43000 non-null  float64
 11  previous           43000 non-null  float64
 12  poutcome           43000 non-null  object
 13  emp.var.rate       43000 non-null  float64
 14  cons.price.idx     42529 non-null  object
 15  cons.conf.idx      43000 non-null  object
 16  euribor3m          33744 non-null  object
 17  nr.employed        43000 non-null  object
 18  subscribe          43000 non-null  object
 19  date               42752 non-null  object
 20  latitude           43000 non-null  float64
 21  longitude          43000 non-null  float64
 22  id                 43170 non-null  object
 23  income             43170 non-null  int64
 24  kidhome            43170 non-null  int64
 25  teenhome           43170 non-null  int64
 26  dt_customer        43170 non-null  datetime64[ns]
 27  numwebvisitsmonth  43170 non-null  int64
dtypes: datetime64[ns](1), float64(11), int64(4), object(12)
memory usage: 9.2+ MB

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,subscribe,date,latitude,longitude,id,income,kidhome,teenhome,dt_customer,numwebvisitsmonth
0,22.0,services,SINGLE,high.school,0.0,1.0,0.0,telephone,94.0,2.0,999.0,0.0,NONEXISTENT,-2.9,"92,963","-40,8",NaN,"5076,2",no,23-enero-2018,37.753,-110.119,0000e811-006e-4404-b535-89bf6cd96553,101916,2,0,2014-07-17,3
1,56.0,technician,DIVORCED,professional.course,0.0,0.0,0.0,cellular,464.0,1.0,3.0,2.0,SUCCESS,-1.1,"94,601","-49,5",1,"4963,6",yes,2-diciembre-2018,27.766,-89.350,0000ea53-e9b2-4b3f-9f4b-058f37e5fab8,57990,2,2,2014-01-04,3
2,31.0,blue-collar,MARRIED,basic.9y,0.0,0.0,0.0,cellular,365.0,2.0,999.0,0.0,NONEXISTENT,-1.8,"92,893","-46,2",NaN,"5099,1",no,13-enero-2015,36.347,-69.175,000165f9-20c0-4cb5-bd47-6233b92655c1,175137,1,1,2014-12-01,8
3,38.0,blue-collar,SINGLE,university.degree,0.0,0.0,0.0,telephone,109.0,1.0,999.0,0.0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2-septiembre-2015,26.893,-68.620,00024507-c59b-4eee-86d5-cc341b96eb6d,62489,2,0,2012-01-25,7
4,39.0,entrepreneur,MARRIED,basic.6y,0.0,1.0,0.0,cellular,265.0,2.0,16.0,1.0,SUCCESS,-3.4,"92,379","-29,8","0,819","5017,5",yes,30-abril-2018,48.901,-96.742,0004e1d1-958d-4abf-a57c-9b9c7be887a0,169187,2,2,2014-05-12,16

Realizo últimas operaciones de limpieza o mejora de visualización de datos

In [ ]:
#Mejoro visibilidad de variables buleanas 'default','housing' y 'loan' para que muestren
#un valor booleano limpio sin decimales y en datos vacíos o NaN muestre un 0.
cols = ['default', 'housing', 'loan']
# Reemplazar valores vacíos o NaN con 0 y convertir todos los valores a enteros
df_merged[cols] = df_merged[cols].replace({'': 0}).fillna(0).astype(int)
# En columna date:
# Renombro columna por call_date para mayor claridad
df_merged.rename(columns={'date': 'call_date'}, inplace=True)
# Convertir la columna 'call_date' a tipo datetime para facilitar análisis posteriores
# para ello he utilizado la librería locale y una función de pandas, que he buscado en ChatGPT
import locale
locale.setlocale(locale.LC_TIME, 'Spanish_Spain')  # Windows (alternativa)
df_merged['call_date'] = pd.to_datetime(df_merged['call_date'], format='%d-%B-%Y', errors='coerce')


# Verificar resultado
df_merged.info()
#Hecho un vistazo a la cantidad de valores nulos
df_merged.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                37880 non-null  float64
 1   job                42655 non-null  object
 2   marital            42915 non-null  object
 3   education          41193 non-null  object
 4   default            43170 non-null  int32
 5   housing            43170 non-null  int32
 6   loan               43170 non-null  int32
 7   contact            43000 non-null  object
 8   duration           43000 non-null  float64
 9   campaign           43000 non-null  float64
 10  pdays              43000 non-null  float64
 11  previous           43000 non-null  float64
 12  poutcome           43000 non-null  object
 13  emp.var.rate       43000 non-null  float64
 14  cons.price.idx     42529 non-null  object
 15  cons.conf.idx      43000 non-null  object
 16  euribor3m          33744 non-null  object
 17  nr.employed        43000 non-null  object
 18  subscribe          43000 non-null  object
 19  call_date          42752 non-null  datetime64[ns]
 20  latitude           43000 non-null  float64
 21  longitude          43000 non-null  float64
 22  id                 43170 non-null  object
 23  income             43170 non-null  int64
 24  kidhome            43170 non-null  int64
 25  teenhome           43170 non-null  int64
 26  dt_customer        43170 non-null  datetime64[ns]
 27  numwebvisitsmonth  43170 non-null  int64
dtypes: datetime64[ns](2), float64(8), int32(3), int64(4), object(11)
memory usage: 8.7+ MB

age                  5290
job                   515
marital               255
education            1977
default                 0
housing                 0
loan                    0
contact               170
duration              170
campaign              170
pdays                 170
previous              170
poutcome              170
emp.var.rate          170
cons.price.idx        641
cons.conf.idx         170
euribor3m            9426
nr.employed           170
subscribe             170
call_date             418
latitude              170
longitude             170
id                      0
income                  0
kidhome                 0
teenhome                0
dt_customer             0
numwebvisitsmonth       0
dtype: int64

In [ ]:
#Visualizo las primeras filas del DataFrame denifitivo
df_merged.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,subscribe,call_date,latitude,longitude,id,income,kidhome,teenhome,dt_customer,numwebvisitsmonth
0,22.0,services,SINGLE,high.school,0,1,0,telephone,94.0,2.0,999.0,0.0,NONEXISTENT,-2.9,"92,963","-40,8",NaN,"5076,2",no,2018-01-23,37.753,-110.119,0000e811-006e-4404-b535-89bf6cd96553,101916,2,0,2014-07-17,3
1,56.0,technician,DIVORCED,professional.course,0,0,0,cellular,464.0,1.0,3.0,2.0,SUCCESS,-1.1,"94,601","-49,5",1,"4963,6",yes,2018-12-02,27.766,-89.350,0000ea53-e9b2-4b3f-9f4b-058f37e5fab8,57990,2,2,2014-01-04,3
2,31.0,blue-collar,MARRIED,basic.9y,0,0,0,cellular,365.0,2.0,999.0,0.0,NONEXISTENT,-1.8,"92,893","-46,2",NaN,"5099,1",no,2015-01-13,36.347,-69.175,000165f9-20c0-4cb5-bd47-6233b92655c1,175137,1,1,2014-12-01,8
3,38.0,blue-collar,SINGLE,university.degree,0,0,0,telephone,109.0,1.0,999.0,0.0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-09-02,26.893,-68.620,00024507-c59b-4eee-86d5-cc341b96eb6d,62489,2,0,2012-01-25,7
4,39.0,entrepreneur,MARRIED,basic.6y,0,1,0,cellular,265.0,2.0,16.0,1.0,SUCCESS,-3.4,"92,379","-29,8","0,819","5017,5",yes,2018-04-30,48.901,-96.742,0004e1d1-958d-4abf-a57c-9b9c7be887a0,169187,2,2,2014-05-12,16

In [ ]:
#Con todo el set unido y limpio reviso las estadísticas numéricas

df_merged.describe().T

,count,mean,min,25%,50%,75%,max,std
age,37880.0,39.977112,17.0,32.0,38.0,47.0,98.0,10.437957
default,43170.0,0.000069,0.0,0.0,0.0,0.0,1.0,0.008336
housing,43170.0,0.521149,0.0,0.0,1.0,1.0,1.0,0.499558
loan,43170.0,0.151309,0.0,0.0,0.0,0.0,1.0,0.358354
duration,43000.0,257.739279,0.0,102.0,179.0,319.0,4918.0,258.666033
campaign,43000.0,2.567233,1.0,1.0,2.0,3.0,56.0,2.772294
pdays,43000.0,962.330953,0.0,999.0,999.0,999.0,999.0,187.260394
previous,43000.0,0.174023,0.0,0.0,0.0,0.0,7.0,0.497366
emp.var.rate,43000.0,0.077128,-3.4,-1.8,1.1,1.4,1.4,1.573898
call_date,42752,2017-07-01 19:55:11.676646912,2015-01-01 00:00:00,2016-04-01 00:00:00,2017-07-04 00:00:00,2018-10-01 06:00:00,2019-12-31 00:00:00,NaN
latitude,43000.0,36.856697,24.396,30.61475,36.761,43.11325,49.384,7.225948
longitude,43000.0,-95.939067,-124.997,-110.49425,-95.8995,-81.42775,-66.937,16.752282
income,43170.0,93227.389622,5841.0,49608.0,93009.5,136740.5,180802.0,50498.181989
kidhome,43170.0,1.004749,0.0,0.0,1.0,2.0,2.0,0.815996
teenhome,43170.0,0.998633,0.0,0.0,1.0,2.0,2.0,0.816008
dt_customer,43170,2013-05-11 22:09:47.407922176,2012-01-01 00:00:00,2012-07-16 00:00:00,2013-03-01 00:00:00,2014-03-28 00:00:00,2014-12-31 00:00:00,NaN
numwebvisitsmonth,43170.0,16.59129,1.0,9.0,17.0,25.0,32.0,9.241769

In [ ]:
#Seguidamente de las estadísticas categóricas
df_merged.describe(include='object').T

                count unique                                   top   freq
job             42655     11                                admin.  10873
marital         42915      3                               MARRIED  25999
education       41193      7                     university.degree  12722
contact         43000      2                              cellular  27396
poutcome        43000      3                           NONEXISTENT  37103
cons.price.idx  42529     26                                93,994   7938
cons.conf.idx   43000     26                                 -36,4   8020
euribor3m       33744    309                                 4,857   2287
nr.employed     43000     11                                5228,1  16980
subscribe       43000      2                                    no  38156
id              43170  43170  0000e811-006e-4404-b535-89bf6cd96553      1

4. Guardo el archivo limpio, a partir del cual voy a realizar todos los analisis y KPIs